### ISSUE TITLE
Adguard DNS for Android instructions missing Static IP fields

### ISSUE THREAD

**Issue by PatMyron** [AdguardTeam/AdguardKnowledgeBase#300]
https://adguard.com/en/adguard-dns/overview.html

After switching the IP settings from DHCP to Static, these fields need to be filled out in addition to `DNS 1` and `DNS 2`:

    IP address
    Gateway
    Network prefix length

What values should be inputted for these fields?

**Comment by ameshkov** [comment]
@PatMyron hi, you shouldn't change them, just keep the same values as you have there.

**Comment by PatMyron** [comment]
@ameshkov If I fill these fields with the default grayed out values, I lose internet connection:

![screenshot_20190220-103750](https://user-images.githubusercontent.com/7014355/53103547-d666ae80-34fb-11e9-8d35-dd1693f50602.png)

**Comment by ameshkov** [comment]
@PatMyron uh, I thought you're talking about your router settings.

Well, maybe your router requires using DHCP configuration...

Tbh, I'd suggest using an external app instead of configuring this all in Wi-Fi settings.

Here are your options:

* [Intra](https://getintra.org) will let you use AdGuard DNS with DNS-over-HTTPS.
* AdGuard for Android [beta](https://adguard.com/beta.html) provides custom DNS settings and supports all DNS encryption protocols.
