### ISSUE TITLE
Display DNS servers up time status on providers page

### ISSUE THREAD

**Issue by KizunaH** [AdguardTeam/AdguardKnowledgeBase#537]
>@ameshkov @vbagirov I am starting to think that we should have a special section for small personal DNS resolvers. We won't be able to monitor their availability and this should be clear to people who read that document.

>@ameshkov Put DNS providers IPs and domains to availability monitoring service or other own thing and do some html,css magic then display "Up or Down" status button (easy) or many days status in a row for each on KB static site.

See https://github.com/AdguardTeam/AdguardKnowledgeBase/pull/526

Display DNS servers up time status on providers page
(this can be either status button or long term detailed status)

https://servers.opennicproject.org/

![image](https://user-images.githubusercontent.com/63988538/87428960-10b77b00-c61e-11ea-8fc1-e67ed9900d47.png)
![image](https://user-images.githubusercontent.com/63988538/87428907-fb425100-c61d-11ea-9445-33c6eb31e3e7.png)

**Comment by ameshkov** [comment]
The problem is that the knowledge base is static, it'd be rather hard to do this.

The solution would be to **create** a DNS monitoring service that will:

1. Calculate DNS servers uptime
2. Return a dynamic image with the uptime value.

I think this is kinda overkill, but maybe there's already something like this?

**Comment by mHatsune** [comment]
> The problem is that the knowledge base is static, it'd be rather hard to do this.
> The solution would be to **create** a DNS monitoring service that will:
> 1. Calculate DNS servers uptime
> 2. Return a dynamic image with the uptime value.
> 
> I think this is kinda overkill, but maybe there's already something like this?

There're paid services offer customizable embed features to show metric graphs on other sites but those are expensive with amount of monitors and currently KB site contain nearly 30 providers. Some cheap up time monitoring services have APIs then possible to combine with one more third-party service and embed each dynamic content to KB site. 
Otherwise it's possible to customize opensource monitoring project for that purpose. Last, your idea also good.

**Comment by vbagirov** [comment]
@ameshkov are we going to implement something like that or is it better to close the issue?

**Comment by KizunaH** [comment]
> @ameshkov are we going to implement something like that or is it better to close the issue?

@vbagirov I'm going to close this. All existing DNS projects in KB site have their own websites and some are display status as well. This came into consideration due PR similar https://github.com/AdguardTeam/AdguardKnowledgeBase/pull/526 (no project status, website etc similar opennic servers)
